stages:
  - apply
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform init
apply:
  stage: apply
  script:
    - ls -la
    - terraform init -chdir=management_instance/tenants/tagsets/s3backend -backend-config="key=tagsets" -backend-config="bucket=$BUCKET_NAME" -backend-config="region=$BUCKET_REGION"
    - terraform apply -chdir=management_instance/tenants/tagsets/s3backend -auto-approve -var=octopus_server=$OCTOPUS_URL -var=octopus_apikey=$OCTOPUS_API_KEY -var=octopus_space_id=$OCTOPUS_SPACE