stages:
  - apply:tagsets
  - apply:accounts
  - apply:environments
  - apply:feeds
  - apply:libraryvariablesets
  - apply:projects
  - apply:tenants
  - octopus
image:
  name: hashicorp/terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
tagsets:
  stage: apply:tagsets
  script:
    - echo "Apply Tag Sets"
    - |
      terraform \
      -chdir=management_instance/tenants/tagsets/s3backend \
      init \
      -backend-config="key=tagsets" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/tenants/tagsets/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
accounts:
  stage: apply:accounts
  script:
    - echo "Apply Accounts"
    - |
      terraform \
      -chdir=shared/accounts/aws/s3backend \
      init \
      -backend-config="key=aws_account" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=shared/accounts/aws/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=aws_access_key=$AWS_ACCESS_KEY_ID \
      -var=aws_secret_key=$AWS_SECRET_ACCESS_KEY
environments:
  stage: apply:environments
  script:
    - echo "Apply Environments"
    - |
      terraform \
      -chdir=management_instance/environments/production/s3backend \
      init \
      -backend-config="key=environments" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/environments/production/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
feeds:
  stage: apply:feeds
  script:
    - echo "Apply Feeds"
    - |
      terraform \
      -chdir=shared/feeds/github/s3backend \
      init \
      -backend-config="key=feeds" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=shared/feeds/github/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=feed_github_password=$GH_TOKEN
    - |
      terraform \
      -chdir=shared/feeds/dockerhub/s3backend \
      init \
      -backend-config="key=dockerhubfeeds" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=shared/feeds/dockerhub/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=docker_username=$DOCKER_USERNAME \
      -var=docker_password=$DOCKER_PASSWORD
libraryvariablesets:
  stage: apply:libraryvariablesets
  script:
    - echo "Apply Library Variable Sets"
    - |
      terraform \
      -chdir=management_instance/variables/octopus_server/s3backend \
      init \
      -backend-config="key=docker_hub_variables" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/variables/octopus_server/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
    - |
      terraform \
      -chdir=management_instance/variables/docker/s3backend \
      init \
      -backend-config="key=octopus_docker_variables" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/variables/docker/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
    - |
      terraform \
      -chdir=management_instance/variables/azure/s3backend \
      init \
      -backend-config="key=octopus_azure_variables" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/variables/azure/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
    - |
      terraform \
      -chdir=management_instance/variables/config_as_code/s3backend \
      init \
      -backend-config="key=octopus_cac_variables" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/variables/config_as_code/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
    - |
      terraform \
      -chdir=management_instance/project_groups/azure_web_app/s3backend \
      init \
      -backend-config="key=octopus_azure_project_group" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/project_groups/azure_web_app/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
projects:
  stage: apply:projects
  script:
    - apk add --update-cache bash jq curl
    - ./bash/clear_projects.sh
    - |
      terraform \
      -chdir=management_instance/projects/azure_logs/s3backend \
      init \
      -backend-config="key=azure_logs_project" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/projects/azure_logs/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=bucket_name=$BUCKET_NAME \
      -var=bucket_region=$BUCKET_REGION
    - echo "Applying init_space project"
    - |
      terraform \
      -chdir=management_instance/projects/init_space/s3backend \
      init \
      -backend-config="key=environments_project" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/projects/init_space/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=bucket_name=$BUCKET_NAME \
      -var=bucket_region=$BUCKET_REGION
    - echo "Applying azure_web_app_unmanaged_cac project"
    - |
      terraform \
      -chdir=management_instance/projects/azure_web_app_unmanaged_cac/s3backend \
      init \
      -backend-config="key=azure_web_app_unmanaged_cac" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/projects/azure_web_app_unmanaged_cac/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=bucket_name=$BUCKET_NAME \
      -var=bucket_region=$BUCKET_REGION
    - echo "Applying unmanaged_azure_web_app_project project"
    - |
      terraform \
      -chdir=management_instance/projects/azure_web_app_unmanaged/s3backend \
      init \
      -backend-config="key=unmanaged_azure_web_app_project" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/projects/azure_web_app_unmanaged/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=bucket_name=$BUCKET_NAME \
      -var=bucket_region=$BUCKET_REGION
tenants:
  stage: apply:tenants
  script:
    - |
      terraform \
      -chdir=management_instance/tenants/europe/s3backend \
      init \
      -backend-config="key=tenants" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/tenants/europe/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=docker_username=$DOCKER_USERNAME \
      -var=docker_password=$DOCKER_PASSWORD \
      -var=azure_application_id=$AZURE_APPLICATION_ID \
      -var=azure_subscription_id=$AZURE_SUBSCRIPTION_ID \
      -var=azure_password=$AZURE_PASSWORD \
      -var=azure_tenant_id=$AZURE_TENANT_ID \
      -var=cac_username=$CAC_GH_USERNAME \
      -var=cac_password=$CAC_GH_TOKEN \
      -var=cac_url=$CAC_GH_URL
    - |
      terraform \
      -chdir=management_instance/tenants/america/s3backend \
      init \
      -backend-config="key=tenants_america" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/tenants/america/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=docker_username=$DOCKER_USERNAME \
      -var=docker_password=$DOCKER_PASSWORD \
      -var=azure_application_id=$AZURE_APPLICATION_ID \
      -var=azure_subscription_id=$AZURE_SUBSCRIPTION_ID \
      -var=azure_password=$AZURE_PASSWORD \
      -var=azure_tenant_id=$AZURE_TENANT_ID \
      -var=cac_username=$CAC_GH_USERNAME \
      -var=cac_password=$CAC_GH_TOKEN \
      -var=cac_url=$CAC_GH_URL
octopus:
  stage: octopus
  image:
    name: octopusdeploy/octo
    entrypoint: [""]
  script:
    - octo list-projects --server=$OCTOPUS_URL --apiKey=$OCTOPUS_API_KEY --space $OCTOPUS_SPACE