stages:
  - apply
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
  - terraform init
apply:
  stage: apply
  script:
    # Accounts
    - |
      terraform \
      -chdir=management_instance/tenants/tagsets/s3backend \
      init \
      -backend-config="key=tagsets" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/tenants/tagsets/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE
    # Environments
    - |
      terraform \
      -chdir=management_instance/environments/production/s3backend \
      init \
      -backend-config="key=aws_account" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=management_instance/environments/production/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=aws_access_key=$AWS_ACCESS_KEY_ID \
      -var=aws_secret_key=$AWS_SECRET_ACCESS_KEY
    # Feeds
    - |
      terraform \
      -chdir=shared/feeds/github/s3backend \
      init \
      -backend-config="key=feeds" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=shared/feeds/github/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$OCTOPUS_SPACE \
      -var=feed_github_password=$GH_TOKEN
    - |
      terraform \
      -chdir=shared/feeds/dockerhub/s3backend \
      init \
      -backend-config="key=dockerhubfeeds" \
      -backend-config="bucket=$BUCKET_NAME" \
      -backend-config="region=$BUCKET_REGION"
    - |
      terraform \
      -chdir=shared/feeds/dockerhub/s3backend \
      apply \
      -auto-approve \
      -var=octopus_server=$OCTOPUS_URL \
      -var=octopus_apikey=$OCTOPUS_API_KEY \
      -var=octopus_space_id=$.OCTOPUS_SPACE \
      -var=docker_username=$DOCKER_USERNAME \
      -var=docker_password=$DOCKER_PASSWORD
    # Library Variable Sets