name: Configure Management Instance
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: hashicorp/setup-terraform@v2

      # Environments
      - run: >
          terraform init
          -backend-config="key=environments"
          -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
          -backend-config="region=${{ secrets.BUCKET_REGION }}"
        working-directory: management_instance/environments/production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - run: >
          terraform apply -auto-approve
          -var=octopus_server=${{ secrets.OCTOPUS_URL }}
          -var=octopus_apikey=${{ secrets.OCTOPUS_API_KEY }}
          -var=octopus_space_id=${{ secrets.OCTOPUS_SPACE }}
        working-directory: management_instance/environments/production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # Feeds
      - run: >
          terraform init
          -backend-config="key=feeds"
          -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
          -backend-config="region=${{ secrets.BUCKET_REGION }}"
        working-directory: management_instance/feeds/github
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - run: >
          terraform apply -auto-approve
          -var=octopus_server=${{ secrets.OCTOPUS_URL }}
          -var=octopus_apikey=${{ secrets.OCTOPUS_API_KEY }}
          -var=octopus_space_id=${{ secrets.OCTOPUS_SPACE }}
        working-directory: management_instance/feeds/github
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
permissions:
  id-token: write
  checks: write
  contents: write
